-- Migration: Add Bentuk Badan page content keys to site_content
-- Halaman: /bentuk-badan (Set Mini Sauna Legend)

INSERT INTO site_content (id, value) VALUES
  ('bentuk_badan_hero_badge', 'Produk Luaran'),
  ('bentuk_badan_hero_title', 'Bentuk Badan'),
  ('bentuk_badan_hero_title_highlight', 'Ideal'),
  ('bentuk_badan_hero_desc', 'Set penjagaan badan yang memberi kesan panas seperti bersauna. Mengandungi losyen Mustajab Extra Hot, Super Hot dan Extreme Hot — tahap kepanasan berbeza untuk membantu metabolisme, bakar lemak dan kurangkan selulit.'),
  ('bentuk_badan_intro_label', 'Set Mini Sauna Legend'),
  ('bentuk_badan_intro_title', 'Kesan Panas Seperti Bersauna\nUntuk Bentuk Badan Yang Diingini'),
  ('bentuk_badan_intro_p1', 'Sesuai dengan nama yang diberi, Set Mini Sauna adalah set penjagaan badan yang memberi kesan panas bagi mendapatkan khasiat seperti ketika anda sedang bersauna. Mengandungi 3 Losyen Mustajab — Extra Hot, Super Hot dan Extreme Hot — bersaiz 130ml setiap jenis.'),
  ('bentuk_badan_intro_p2', 'Tahap kepanasan berbeza bertindak sebagai ejen yang dapat meningkatkan kadar metabolisme badan dan seterusnya boleh membantu membakar lemak serta membantu mengurangkan selulit di bahagian perut, peha, pinggul dan lain-lain tempat yang diperlukan.'),
  ('bentuk_badan_tips_label', 'Khasiat & Kegunaan'),
  ('bentuk_badan_tips_title', 'Kebaikan Set Mini Sauna'),
  ('bentuk_badan_tip_1_icon', '🔥'),
  ('bentuk_badan_tip_1_title', 'Tingkat Metabolisme'),
  ('bentuk_badan_tip_1_desc', 'Kesan panas membantu meningkatkan kadar metabolisme badan untuk pembakaran lemak yang lebih efisien.'),
  ('bentuk_badan_tip_2_icon', '💪'),
  ('bentuk_badan_tip_2_title', 'Bakar Lemak'),
  ('bentuk_badan_tip_2_desc', 'Digunakan bersama bengkung, korset atau girdle — amat digalakkan berserta senaman ringan untuk kesan optimum.'),
  ('bentuk_badan_tip_3_icon', '✨'),
  ('bentuk_badan_tip_3_title', 'Kurangkan Selulit'),
  ('bentuk_badan_tip_3_desc', 'Sapu pada bahagian bermasalah seperti perut, lengan, peha dan pinggul — urutan pusingan seperti jam sebelum bengkung.'),
  ('bentuk_badan_tip_4_icon', '🏃'),
  ('bentuk_badan_tip_4_title', 'Sesuai Bersenam'),
  ('bentuk_badan_tip_4_desc', 'Super Hot & Extreme Hot sesuai disapu ketika bersenam atau bersukan — kehangatan tahan lama membantu pembakaran.'),
  ('bentuk_badan_tip_5_icon', '🩹'),
  ('bentuk_badan_tip_5_title', 'Singkir Angin'),
  ('bentuk_badan_tip_5_desc', 'Ekstrak halia membantu mengeluarkan angin dalam badan dan memberi keselesaan pada perut, urat dan otot.'),
  ('bentuk_badan_tip_6_icon', '⏰'),
  ('bentuk_badan_tip_6_title', 'Mudah & Praktikal'),
  ('bentuk_badan_tip_6_desc', 'Boleh digunakan waktu pagi sebelum aktiviti atau bila-bila masa. Tidak berminyak, cepat menyerap.'),
  ('bentuk_badan_article_1_title', 'Extra Hot — Tahap Panas 3'),
  ('bentuk_badan_article_1_content', 'Diformulasikan dengan lebih ekstrak halia untuk tahap panas pertengahan. Amat sesuai untuk mereka yang inginkan bentuk badan yang ideal. Pemakaian bengkung atau korset amat digalakkan. Urutan pusingan seperti jam pada perut sebelum bengkung untuk kesan optimum.'),
  ('bentuk_badan_article_2_title', 'Super Hot — Tahap Panas 4'),
  ('bentuk_badan_article_2_content', 'Dengan tambahan Capsicum untuk kehangatan yang lebih tinggi. Sesuai untuk surirumah dengan aktiviti harian dan kegunaan ketika bersenam. Mengekalkan kehangatan ketika berpeluh dan membantu membakar lemak dengan lebih efisien. Boleh disapu nipis sebelum aktiviti bermula.'),
  ('bentuk_badan_article_3_title', 'Extreme Hot — Tahap Panas 5'),
  ('bentuk_badan_article_3_content', 'Tahap kepanasan paling tinggi dengan Iso Slim Complex. Menumpukan pada pembentukan dan kecantikan badan. Disyorkan sapu waktu malam sebelum tidur. Sesuai untuk mereka yang tahan panas dan mahukan kesan maksimum.'),
  ('bentuk_badan_gallery_label', 'Galeri'),
  ('bentuk_badan_gallery_title', 'Kegunaan & Cara Pakai'),
  ('bentuk_badan_produk_label', 'Produk Disyorkan'),
  ('bentuk_badan_produk_title', 'Set Mini Sauna Legend'),
  ('bentuk_badan_produk_desc', 'Extra Hot, Super Hot & Extreme Hot — pilihan losyen untuk bentuk badan ideal'),
  ('bentuk_badan_quote', 'Ketiga-tiga losyen ini adalah best seller dan kini hadir dalam Set Premium Mini Sauna Legend dengan harga mampu milik. Jaga pemakanan sihat, elakkan makanan manis dan bergas, serta lakukan senaman untuk kekal cergas dan cantik menawan.'),
  ('bentuk_badan_quote_author', '— Dunia Herbs'),
  ('bentuk_badan_cta_title', 'Dapatkan Bentuk Badan Ideal Anda'),
  ('bentuk_badan_cta_desc', 'Hubungi kami untuk nasihat produk yang sesuai. Kami sedia membantu.'),
  ('bentuk_badan_product_ids', ''),
  ('bentuk_badan_produk_legend_ids', '')
ON CONFLICT (id) DO NOTHING;
