-- Migration: Add Seisi Keluarga page content keys to site_content
-- Halaman: /seisi-keluarga (Losyen Mustajab Pati Halia — Legend & Haruman)

INSERT INTO site_content (id, value) VALUES
  ('seisi_keluarga_hero_badge', 'Losyen Pati Halia'),
  ('seisi_keluarga_hero_title', 'Kegunaan'),
  ('seisi_keluarga_hero_title_highlight', 'Seisi Keluarga'),
  ('seisi_keluarga_hero_desc', 'Losyen Mustajab Ekstrak Halia adalah losyen pertama keluaran Dunia Herbs seterusnya menjadi peneraju utama dalam pengeluaran losyen hangat berasaskan halia. Kegunaan seisi keluarga dan losyen serbaguna — harus dimiliki oleh setiap isi rumah.'),
  ('seisi_keluarga_intro_label', 'Losyen Mustajab Pati Halia'),
  ('seisi_keluarga_intro_title', 'Perintis Losyen Pati Halia' || chr(10) || 'Sejak 2005'),
  ('seisi_keluarga_intro_p1', 'Sejak mula diperkenalkan pada tahun 2005, Losyen Mustajab Pati Halia Dunia Herbs menjadi perintis bagi produk losyen berasaskan pati halia. Losyen ini bersifat tidak melekit dan cepat meresap pada kulit serta mempunyai kehangatan yang sederhana.'),
  ('seisi_keluarga_intro_p2', 'Halia atau nama saintifiknya Zingiber officinale dari keluarga Zingiberaceae kaya dengan kandungan kalium, fosforus dan kalsium, protein, karbohidrat, gentian, vitamin C dan niasin. Khasiat halia dalam merawat pelbagai penyakit bukan saja diketahui menerusi kaedah tradisional malah telah dibuktikan oleh pakar-pakar perubatan moden.'),
  ('seisi_keluarga_tips_label', 'Khasiat & Kegunaan'),
  ('seisi_keluarga_tips_title', 'Kebaikan Losyen Pati Halia'),
  ('seisi_keluarga_tip_1_icon', '💆'),
  ('seisi_keluarga_tip_1_title', 'Digunakan Untuk Tujuan Urutan'),
  ('seisi_keluarga_tip_1_desc', 'Sesuai untuk urutan badan, sendi dan otot. Kehangatan halia membantu melancarkan pengaliran darah dan melegakan ketidakselesaan.'),
  ('seisi_keluarga_tip_2_icon', '🔄'),
  ('seisi_keluarga_tip_2_title', 'Boleh Digunakan Sekerap Mungkin'),
  ('seisi_keluarga_tip_2_desc', 'Tidak berminyak dan cepat meresap. Gunakan secara konsisten dibantu dengan senaman ringan untuk kesan optimum.'),
  ('seisi_keluarga_tip_3_icon', '👨‍👩‍👧‍👦'),
  ('seisi_keluarga_tip_3_title', 'Kegunaan Seisi Keluarga'),
  ('seisi_keluarga_tip_3_desc', 'Sesuai untuk pelbagai lapisan masyarakat. Kecuali bayi. Mudah dibawa kemana sahaja.'),
  ('seisi_keluarga_tip_4_icon', '🩹'),
  ('seisi_keluarga_tip_4_title', 'Legakan Ketidakselesaan'),
  ('seisi_keluarga_tip_4_desc', 'Kandungan aktif Gingeroles dalam halia memberi kesan apabila meresap ke dalam badan. Membantu melegakan sendi dan otot.'),
  ('seisi_keluarga_tip_5_icon', '✨'),
  ('seisi_keluarga_tip_5_title', 'Serbaguna & Praktikal'),
  ('seisi_keluarga_tip_5_desc', 'Satu produk untuk pelbagai kegunaan — urutan, ketidakselesaan badan, angin dalam badan. Sesuai untuk rutin harian.'),
  ('seisi_keluarga_tip_6_icon', '🕐'),
  ('seisi_keluarga_tip_6_title', '20 Tahun Di Pasaran'),
  ('seisi_keluarga_tip_6_desc', 'Produk perintis Dunia Herbs yang telah dipercayai ramai sejak 2005. KKM & Halal JAKIM.'),
  ('seisi_keluarga_article_1_title', 'Perintis Losyen Pati Halia'),
  ('seisi_keluarga_article_1_content', 'Losyen Mustajab Pati Halia ialah produk pertama keluaran Dunia Herbs dan seterusnya menjadi peneraju utama dalam pengeluaran losyen hangat berasaskan halia di Malaysia. Losyen serbaguna yang harus dimiliki oleh setiap isi rumah.'),
  ('seisi_keluarga_article_2_title', 'Khasiat Halia & Gingeroles'),
  ('seisi_keluarga_article_2_content', 'Menurut kajian, kandungan aktif dalam halia yang dikenali sebagai Gingeroles memberi kesan apabila ia meresap ke dalam badan. Halia membantu melancarkan peredaran darah, mengurangkan bengkak, membuang angin, dan memberikan kehangatan semula jadi.'),
  ('seisi_keluarga_article_3_title', 'Sesuai Untuk Semua'),
  ('seisi_keluarga_article_3_content', 'Dari remaja hingga warga emas, losyen ini sesuai untuk pelbagai lapisan masyarakat. Sapuan pada sendi, otot atau abdomen. Untuk luaran sahaja. Tidak sesuai untuk bayi. Harga: SM RM23.00 / SS RM26.00. Kandungan: 130ml.'),
  ('seisi_keluarga_umrah_title', 'Kegunaan Semasa Umrah & Haji'),
  ('seisi_keluarga_umrah_content', 'Losyen Mustajab Pati Halia amat sesuai dibawa bersama semasa menunaikan umrah atau haji di tanah suci Mekah. Cuaca panas dan perjalanan jauh boleh menyebabkan ketidakselesaan sendi, otot dan angin dalam badan. Sapuan losyen pada bahagian yang dikehendaki dapat membantu melegakan ketidakselesaan dan memberi kehangatan yang menyegarkan. Saiz 130ml mudah dibawa dalam bagasi. Halal JAKIM — sesuai untuk jemaah.'),
  ('seisi_keluarga_gallery_label', 'Galeri'),
  ('seisi_keluarga_gallery_title', 'Kegunaan & Cara Pakai'),
  ('seisi_keluarga_produk_label', 'Produk Disyorkan'),
  ('seisi_keluarga_produk_title', 'Losyen Pati Halia'),
  ('seisi_keluarga_produk_desc', 'Pilihan losyen pati halia kuning — Legend & Haruman. Sesuai untuk kegunaan seisi keluarga.'),
  ('seisi_keluarga_quote', 'Losyen Mustajab Pati Halia memiliki banyak kelebihan serta kegunaannya. Ianya mudah dibawa kemana sahaja dan sesuai untuk pelbagai lapisan masyarakat. Gunakan secara konsisten dan dibantu dengan senaman ringan, pasti peroleh kesan yang optimum.'),
  ('seisi_keluarga_quote_author', '— Dunia Herbs'),
  ('seisi_keluarga_cta_title', 'Dapatkan Losyen Pati Halia Anda'),
  ('seisi_keluarga_cta_desc', 'Hubungi kami untuk nasihat produk yang sesuai. Kami sedia membantu.'),
  ('seisi_keluarga_product_ids', ''),
  ('seisi_keluarga_produk_legend_ids', '')
ON CONFLICT (id) DO UPDATE SET value = EXCLUDED.value;
