-- Migration: Add Produk Minuman page content keys to site_content
-- Halaman: /produk-minuman (Mustajab Extra Daytox & produk minuman/makanan)
-- Jalankan dalam Supabase SQL Editor

-- Part 1: Main content
INSERT INTO site_content (id, value) VALUES
  ('minuman_hero_badge', 'Produk Minuman'),
  ('minuman_hero_title', 'Cantik Luar'),
  ('minuman_hero_title_highlight', 'Cantik Dalam'),
  ('minuman_hero_desc', 'Tubuh badan kita sering terdedah kepada toksin dari persekitaran setiap hari. Mustajab Extra Daytox membantu proses detoksifikasi badan yang sihat dan berkesan.'),
  ('minuman_intro_label', 'Mustajab Extra Daytox'),
  ('minuman_intro_title', 'Detoks Untuk Badan' || chr(10) || 'Lebih Sihat & Ringan'),
  ('minuman_intro_p1', 'Detoks adalah satu proses pembersihan usus dimana segala toksin, lemak serta lendir yang melekat pada dinding usus dikeluarkan melalui proses pembuangan air besar. Apabila usus bersih dari segala kotoran, barulah tubuh badan dapat menyerap segala nutrien pada tahap yang optimum.'),
  ('minuman_intro_p2', 'Pentingnya amalan detoks untuk penjagaan badan dan mengekalkan kesihatan. Dengan menambahkan makanan kesihatan tambahan dalam pelan detoks seharian, ia dapat membantu untuk proses detoksifikasi badan yang sihat dan berkesan.'),
  ('minuman_tips_label', 'Khasiat & Kegunaan'),
  ('minuman_tips_title', 'Kebaikan Mustajab Extra Daytox'),
  ('minuman_tip_1_icon', '🍽️'),
  ('minuman_tip_1_title', 'Membantu Mengawal Selera Makan'),
  ('minuman_tip_1_desc', 'Mengurangkan rasa lapar dan keinginan untuk mengambil makanan ringan. Badan terasa lebih ringan keesokan harinya.'),
  ('minuman_tip_2_icon', '🧹'),
  ('minuman_tip_2_title', 'Menyingkirkan Bahan Toksik'),
  ('minuman_tip_2_desc', 'Membantu proses detoksifikasi badan — membersihkan toksin, lemak dan lendir yang melekat pada dinding usus.'),
  ('minuman_tip_3_icon', '💚'),
  ('minuman_tip_3_title', 'Membersihkan Kolon'),
  ('minuman_tip_3_desc', 'Usus yang bersih membolehkan tubuh badan menyerap nutrien pada tahap yang optimum untuk kesihatan yang lebih baik.'),
  ('minuman_tip_4_icon', '🎯'),
  ('minuman_tip_4_title', 'Sasaran Berat Badan Ideal'),
  ('minuman_tip_4_desc', 'Membantu mencapai impian untuk mendapatkan bentuk badan yang cantik dan menarik. Mengatasi punca utama kenaikan berat badan.'),
  ('minuman_tip_5_icon', '🌙'),
  ('minuman_tip_5_title', 'Mudah & Praktikal'),
  ('minuman_tip_5_desc', 'Pengambilan 1 sachet setiap malam sebelum tidur akan memudahkan proses pembuangan. Badan terasa lebih ringan keesokan harinya.'),
  ('minuman_tip_6_icon', '✨'),
  ('minuman_tip_6_title', 'Cantik Luar Cantik Dalam'),
  ('minuman_tip_6_desc', 'Produk detoks yang diformulasi untuk penjagaan dalaman. Sesuai untuk rutin harian yang sihat.'),
  ('minuman_article_1_title', 'Apakah Detoks?'),
  ('minuman_article_1_content', 'Detoks adalah satu proses pembersihan usus dimana segala toksin, lemak serta lendir yang melekat pada dinding usus dikeluarkan melalui proses pembuangan air besar. Jika terdedah dengan kerap dan berterusan kepada toksin persekitaran, ia akan melemahkan keupayaan sistem tubuh badan secara semulajadi untuk menyingkirkan toksin.'),
  ('minuman_article_2_title', 'Kenapa Perlu Detoks?'),
  ('minuman_article_2_content', 'Faktor persekitaran dan pemakanan moden boleh menyebabkan pengumpulan toksin yang bakal membawa kepada pelbagai penyakit. Amalan detoks membantu mengekalkan kesihatan dan memastikan badan dapat berfungsi pada tahap optimum.'),
  ('minuman_article_3_title', 'Cara Penggunaan'),
  ('minuman_article_3_content', 'Pengambilan 1 sachet Mustajab Extra Daytox setiap malam sebelum tidur akan memudahkan proses pembuangan. Badan akan terasa lebih ringan keesokan harinya. Kandungan: 15 sachet. Harga: SM RM49.00 / SS RM59.00.'),
  ('minuman_gallery_label', 'Galeri'),
  ('minuman_gallery_title', 'Produk & Kegunaan'),
  ('minuman_produk_label', 'Produk Disyorkan'),
  ('minuman_produk_title', 'Produk Minuman & Makanan'),
  ('minuman_produk_desc', 'Pilihan produk dalaman — detoks, minuman kesihatan dan makanan tambahan'),
  ('minuman_quote', 'Mustajab Extra Daytox akan membantu mencapai impian anda untuk mendapatkan bentuk badan yang cantik dan menarik kerana ianya dapat mengatasi masalah yang menjadi punca utama kenaikan berat badan.'),
  ('minuman_quote_author', '— Dunia Herbs'),
  ('minuman_cta_title', 'Dapatkan Produk Minuman Anda'),
  ('minuman_cta_desc', 'Hubungi kami untuk nasihat produk yang sesuai. Kami sedia membantu.'),
  ('minuman_product_ids', ''),
  ('minuman_produk_legend_ids', '')
ON CONFLICT (id) DO UPDATE SET value = EXCLUDED.value;
